tables:
  enabled: true
  host: "roboRIO-212-FRC.local"
#  host: "127.0.0.1"
  tableName: "TatorVision"

server:
  enabled: true
  port:  8080

vision:
  startVisionScript: >
    v4l2-ctl -c white_balance_auto_preset=1,red_balance=1000,blue_balance=1000,contrast=0,saturation=100,auto_exposure=1,exposure_time_absolute=0,exposure_dynamic_framerate=1,auto_exposure_bias=0

  cameraIndex: 0
  inputRes: [640, 480]
  streamRes: [640, 480]
#  inputRes: [320, 240]
#  streamRes: [320, 240]
  maxFPS: 30
  upsideDown: true

  lowerThreshold: [40.0, 200.0, 200.0]
  upperThreshold: [80.0, 255.0, 255.0]

  minArea: 1000
  maxArea: 10000
  minSolidity: 0.0
  maxSolidity: 1.0

  arcLengthPercentage: 0.01

#  fieldOfView: [62.2, 48.8] # RPI camera FOV
  fieldOfView: [70, 48.8] # RPI camera FOV
  distancePoly: { a: 233.56, b: -105.74, c: 64.401 }
  horizontalAngleOffset: 1.0

  debug: false
  display: CONTOURS

profile: false

display:  false  #display an image on screen

