tables:
  enabled: true
  #host: "roboRIO-2122-FRC.local"
  host: "127.0.0.1"
  tableName: "TatorVision"

server:
  enabled: true
  port:  8080

vision:
  maxFPS: 30
  cameraIndex: 0
  fieldOfView: [120.0, 70.0]
#  fieldOfView: [62.2, 48.8]  #FOV of RPI Camera Module

  #lowerThreshold: [60, 100, 100]  #Thresholds are in HSV format
  #upperThreshold: [100, 255, 255]
  lowerThreshold: [60, 100, 50]  #Thresholds are in HSV format
  upperThreshold: [100, 255, 255]
  minArea: 1000
  maxArea: 100000 # about 1/3 of the screen size (640x480), does not correspond to # of pixels
  arcLengthPercentage:  0.01 # determines how much to simplify contours
  debug:  true  # show debug info on screen/stream

  inputRes: [ 640, 400 ]
  streamRes: [ 640, 400 ]

display:  false  #display an image on screen

