tables:
  enabled: true
  host: "roboRIO-212-FRC.local"
#  host: "127.0.0.1"
  tableName: "TatorVision"

server:
  enabled: true
  port:  8080

vision:
  cameraIndex: 0
  maxFPS: 30

  upsideDown: true
  fieldOfView: [62.2, 48.8] # RPI camera FOV
  verticalCameraAngle: 45.0 # degrees from horizontal
  goalHeight: 72 # (8 * 12) - 24.0
  horizontalAngleOffset: 0.0

  lowerThreshold: [50.0, 5.0, 75.0]
  upperThreshold: [100.0, 255.0, 255.0]
  minArea: 1000
  maxArea: 5000
  arcLengthPercentage: 0.01

  debug: false
  display: CONTOURS

  inputRes: [640, 480]
  streamRes: [640, 480]

  startVisionScript: >
    v4l2-ctl -c auto_exposure=1 -c exposure_time_absolute=5

profiler:
  logToConsole: true

display:  false  #display an image on screen

