tables:
  enabled: true
#  host: "roboRIO-212-FRC.local"
  host: "127.0.0.1"
  tableName: "TatorVision"

server:
  enabled: true
  port:  8080

vision:
  cameraIndex: 0
  maxFPS: 30

  fieldOfView: [62.2, 48.8] # RPI camera FOV
  verticalCameraAngle: 45.0 # degrees from horizontal
  goalHeight: 72 # (8 * 12) - 24.0
  horizontalAngleOffset: 0.0

  lowerThreshold: [0.0, 0.0, 250.0]
  upperThreshold: [255.0, 3.0, 255.0]
  minArea: 500
  maxArea: 3000
  arcLengthPercentage: 0.01

  debug: false
  display: CONTOURS

  inputRes: [640, 480]
  streamRes: [640, 480]

  startVisionScript: /bin/sh ./startVision.sh

display:  false  #display an image on screen

