robotIPAddress: "roboRIO-2122-FRC.local"
networkTableName: "TatorVision"
mjpegPortNumber:  8080
frameDelay: 20  #a little over 30 fps
lowerThreshold: [60, 100, 100]  #Thresholds are in HSV format
upperThreshold: [100, 255, 255]
minArea: 1000
maxArea: 100000 #about 1/3 of the screen size (640x480)
arcLengthPercentage:  0.01