robotIPAddress: "roboRIO-2122-FRC.local"
networkTableName: "TatorVision"
subTableName: "relativeTarget"
mjpegPortNumber:  8080
frameDelay: 30  #prevents flooding the network with MJPEG data, 30 = a little over 30 fps
fieldOfView:  [100, 70] #[x, y] field of view in degrees
targetSize: [20.0, 15.0]  #[width, height] dimensions of target in inches
#lowerThreshold: [60, 100, 100]  #Thresholds are in HSV format
#upperThreshold: [100, 255, 255]
lowerThreshold: [0, 0, 100]  #Thresholds are in HSV format
upperThreshold: [255, 200, 255]
minArea: 1000
maxArea: 100000 #about 1/3 of the screen size (640x480)
arcLengthPercentage:  0.01 #determines how much to simplify contours
display:  true  #whether or not to display any image on screen
stream: true  #whether or not to stream MJPEG data
debug:  true  #whether or not to show debug info on screen/stream