robotIPAddress: "roboRIO-2122-FRC.local"
networkTableName: "TatorVision"
subTableName: "relativeTarget"
mjpegPortNumber:  8080
frameDelay: 30  #prevents flooding the network with MJPEG data, 30 = a little over 30 fps

cameraIndex:  0 #use 0 for first/only camera (use 1 for testing external camera on computer with webcam)

#lowerThreshold: [60, 100, 100]  #Thresholds are in HSV format
#upperThreshold: [100, 255, 255]
lowerThreshold: [0, 0, 100]  #Thresholds are in HSV format
upperThreshold: [255, 200, 255]
minArea: 1000
maxArea: 100000 #about 1/3 of the screen size (640x480), does not correspond to # of pixels
arcLengthPercentage:  0.01 #determines how much to simplify contours

flipX:  true  #flip image from left to right
display:  false  #display an image on screen
stream: true  #stream MJPEG data
debug:  false  #show debug info on screen/stream
inputScale:  1.0  #software scale on input frame
streamScale:  1.0 #software scale on stream image (computed after outputScale)ption